version: '3.8'

services:
  front_mailbuilder:
    image: brandonsev/mailsaw:latest
    command: sh -c "serve -s build -l 3002"
    container_name: front_mailbuilder
    volumes:
      - mailsaw-client-build:/app/build/
    ports:
      - 3002:3002
    env_file:
      - ./.env.production
    environment:
      - NODE_ENV=production

volumes:
  mailsaw-client-build:

networks:
  default:
    name: web
    external: true
